// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuemklmnxshsvruhlafe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1ZW1rbG1ueHNoc3ZydWhsYWZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4Nzk4MzgsImV4cCI6MjA2MzQ1NTgzOH0.3P39bmmpcpFz-qoXEzsAaggf3NcUHYRgJ3UVPVReudg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);